### ISSUE TITLE
Configurable config file location

### ISSUE THREAD

**Issue by martenjacobs** [jippi/docker-pritunl#17]
It would be really helpful if it would be possible to control where the configuration file is located. That way you could mount a volume at `/etc/pritunl` without interfering with the entire `/etc` folder. Mounting a volume instead of the config file directly would make it easier to use this image in a docker-compose stack.

**Comment by jippi** [comment]
Hi! Great idea - I'm open for a PR to fix it 

This is how my own docker-compose configuration looks like

```yml
version: '3.3'
services:
    pritunl:
        container_name: pritunl
        privileged: true
        network_mode: host
        restart: always
        environment:
            - PRITUNL_DONT_WRITE_CONFIG=1
        volumes:
            - './mongodb:/var/lib/mongodb'
            - './pritunl:/var/lib/pritunl'
            - './etc/pritunl.conf:/etc/pritunl.conf'
        image: 'jippi/pritunl:1.29.2051.18'
```
