### ISSUE TITLE
Possibility to provide non-minimal releases inline with Pritunl releases

### ISSUE THREAD

**Issue by mattmckinstry** [jippi/docker-pritunl#34]
Would it be possible to also get the latest Pritunl releases bundled with MongoDB in the the same way as the minimal releases?

We are currently using latest-jammy which is 11 months old. We'd love to be able to move to the latest Pritunl version.

Thanks

**Comment by th12289** [comment]
Hello @mattmckinstry,
i am not the developer and runned in the same issue as you. 
So to be safe for the future, i have migrated the database into 
a seperated mongodb. 


These were my steps for example

cd ~/docker-compose/pritunl/docker-compose.yml

```
### This is the current used config for backupserver ###
services:
  mongo:
    image: mongo:latest
    restart: always
    container_name: pritunldb
    hostname: pritunldb
    network_mode: bridge
#    networks:
#      - host
    volumes:
      - mongo_db:/data/db
#    ports:
#      - 27017:27017

  pritunl:
    image: goofball222/pritunl:latest
    restart: always
    container_name: pritunl
    hostname: pritunl
    depends_on:
        - mongo
    network_mode: bridge
#    networks:
#       - host
    privileged: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.ip_forward=1
#    links:
#      - mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
      - 443:443
      - 1194:1194
      - 1194:1194/udp
#      - 1195:1195/udp
    environment:
      - TZ=CEST
      - MONGODB_URI=mongodb://172.17.0.2:27017/pritunl

#networks:
#  host:
#    external: true

volumes:
 mongo_db:

```

```
###### Backup and Restore Database
##### jump into container
### docker exec -it 4e100f479dfd/bin/bash
#### Backup
### cd /home
###	mongodump --db=pritunl
#### Make Archive
### tar cf pritunldb.tar dump
#### Copy out of container
### docker cp 4e100f479dfd:/home/pritunldb.tar /home/pritunldb.tar
######################## Vorbereitet bis hier ########################
#### Stop old Container - Start new container
### cd ~/pritunl
### docker compose stop
### mv docker-compose.yaml docker-compose.yml.old.bak
### mv pre.docker-compose.yml docker-compose.yml
### docker compose up -d
#### Copy into container
### docker cp /home/pritunldb.tar pritunldb:/home/pritunldb.tar
#### jump into container
### docker exec -it pritunldb /bin/bash
#### Unpack
### cd /home
###	tar xf pritunldb.tar
#### Restore
### mongorestore dump
```
